### ISSUE TITLE
MOTD Issue

### ISSUE THREAD

**Issue by Fishy246** [SpigotMC/BungeeCord#1545]
I am having an issue with the Bungeecord config.yml and the per server MOTD's that are defined in the server's section. When I ping that server, the MOTD from the server.properties is shown but not the one defined in the config. I have tried enabling and disabling ping_passthrough, but both had no effect. I am using the latest build of spigot and bungeecord
### Config.yml
```
groups:
  Fishy246:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: 6000
stats: 8e393aa3-1042-4b7a-9604-6ab0b5aeb63a
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- query_port: 25577
  motd: '&cInferna Network &f» &aComing Soon!'
  tab_list: GLOBAL_PING
  query_enabled: false
  ping_passthrough: false
  default_server: Hub
  bind_local_address: true
  fallback_server: Hub
  host: 0.0.0.0:25565
  max_players: 6000
  tab_size: 60
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
timeout: 30000
connection_throttle: 4000
servers:
  Hub:
    motd: 'This IS A MOTD'
    restricted: false
    address: 0.0.0.0:25566
ip_forward: true
online_mode: true 
```
### Server.properties
```
#Minecraft server properties
#Wed Jul 22 22:17:36 BST 2015
generator-settings=
op-permission-level=4
resource-pack-hash=
allow-nether=false
level-name=Hub
enable-query=false
allow-flight=true
announce-player-achievements=false
server-port=25566
max-world-size=29999984
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=
network-compression-threshold=256
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
hardcore=false
snooper-enabled=true
online-mode=false
resource-pack=
pvp=true
difficulty=1
enable-command-block=false
gamemode=0
player-idle-timeout=0
max-players=20
spawn-monsters=true
generate-structures=false
view-distance=10
spawn-protection=16
motd=
```
### What The Response Is
![Image of Issue](http://i.imgur.com/j6XWdHB.png)
