### ISSUE TITLE
Server connection over domain instead of ip fails if ip changed

### ISSUE THREAD

**Issue by Hackebein** [SpigotMC/BungeeCord#1619]
Excerpt from my config.yml (Test System):
```yaml
servers:
  lobby:
    motd: '&1Server: Lobby'
    address: lobby:25565
    restricted: false
  test1:
    motd: '&1Server: test1'
    address: test1:25565
    restricted: false
  test2:
    motd: '&1Server: test2'
    address: test2:25565
    restricted: false
```
Reproduction (Linux):
- Start a game server (spigot)
- Wear the IP of the Games server in your DNS
- Start BungeeCord
- Change the IP of the game server
- Update the entry in your DNS
- BungeeCord tries to establish on the old IP of the server to connect games

Try and Errors:
`-Dsun.net.inetaddr.ttl=0` as start param and the property `networkaddress.cache.ttl=0` in my `lib/security/java.security` doesn't fix it.

Temporary Troubleshooting:
Reload (/greload) the configuration fix it. The Problem now is the red warning and not supportet issues.

My guess:
I suspect that the problem when loading the configuration is. After loading the configuration the domain is resolved only once. And then continues to work only with the IP.

BungeeCord Version: Last stable Build [Build 1088 (Oct 14, 2015 4:10:08 PM)]
