### ISSUE TITLE
forced_hosts ignores restricted setting

### ISSUE THREAD

**Issue by drakmirv** [SpigotMC/BungeeCord#1821]
When using the forced_hosts permissions aren't checked for access to the system.  While my users are forbidden from accessing the restricted server via the "/server" command and with BungeePortals, direct access to the hostname will gain them access.

Is this expected, or do I have something misconfigured?

```
ip_forward: true
network_compression_threshold: 256
stats: <<STATSGUID>>
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - freebungeechat.chat.color
  - freebungeechat.chat.bbcode
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeetablistplus.admin
  - bungeetablistplus.hide
  - freebungeechat.admin
  - serverlistplus.admin
  - bungeecord.server.server6
  - bungeecord.server.server5
  - bungeecord.server.server1
  - bungeecord.server.server2
  - bungeecord.server.server3
  - bungeecord.server.server4
  - bungeepexbridge.reload
  - bungeealiases.reload
groups:
  <<USER>>:
  - default
servers:
  - hub
  bind_local_address: true
  tab_list: SERVER
  query_enabled: true
  host: 0.0.0.0:25565
  forced_hosts:
    hub.<<DOMAIN>>: hub
    server1.<<DOMAIN>>: server1
    server3.<<DOMAIN>>: server3
    server2.<<DOMAIN>>: server2
    server5.<<DOMAIN>>: server5
    server4.<<DOMAIN>>: server4
    server6.<<DOMAIN>>: server6
  max_players: 20
  tab_size: 34
  ping_passthrough: true
  force_default_server: false
  motd: ''
player_limit: -1
online_mode: true
log_commands: false
disabled_commands: []
connection_throttle: 4000
```
