### ISSUE TITLE
Forced Hosts Not Working

### ISSUE THREAD

**Issue by EazyFTW** [SpigotMC/BungeeCord#1947]
My Forced Hosted are Not Working i set up a SRV name and everything, my ip`s have a port p.s.

My Bungee Config:
```
ip_forward: true
network_compression_threshold: 256
stats: 29d32b23-1866-4673-ba61-71d2b1f0e206
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - serverchecker.notify
  - chatemoji.use
  - ultimatereport.commands.report
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - serverchecker.notify
  - chatemoji.use
  - cdispatch.*
  - banmanager.master
  - btc.reload
  - btc.list
  - btc.version
  - btc.help
  - bungeecord.command.announce
  - bungeecord.command.warn
  - bungeecord.command.sendtitle
  - bungeecord.command.sendaction
  - closedserver.admin
  - closedserver.bypass
  - bungeecord.command.send
  - bungeecord.command.find
  - ultimatereport.commands.report
  - ultimatereport.bypass.report
  - ultimatereport.reports.notify
  - ultimatereport.offline.notify
  - SuperAntiAd.admins
  - SuperAntiAd.bypass
  - commandspy.use
  - bungee.commandspy
  - socialspy.use
  - bungee.socialspy
  - servermanager.servers.delete
  - servermanager.help
  - servermanager.servers.reload
  - servermanager.servers.list
  - servermanager.servers.info
  - servermanager.servers.enable
  - servermanager.servers.disable
  - servermanager.servers.setlobby
  - servermanager.servers.kick
  - servermanager.servers.ignorekick
  - servermanager.goto
groups:
  EazyFTW:
  - admin
  oSplatz:
  - admin
  SuperSongVo:
  - admin
servers:
  Paintball:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  HG:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  Pixelmon:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  PvP:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  Hub:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  TurfWars:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  GoldRush:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  Creative:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
  SkyWars:
    motd: ''
    address: XXXXXXXXXXXXXXXXXX
    restricted: false
timeout: 30000
listeners:
- query_port: 26287
  motd: IfBjRE
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    skywars.psychedelicpvp.com: SkyWars
  ping_passthrough: false
  bind_local_address: true
  host: s20.minespan.com:26287
  max_players: 100
  tab_size: 60
  force_default_server: true
  priorities:
  - Hub
player_limit: -1
online_mode: true
log_commands: true
disabled_commands:
- pl
connection_throttle: -1
```
