### ISSUE TITLE
[Ping Handler] -> <server name> - read timed out 

### ISSUE THREAD

**Issue by koca2000** [SpigotMC/BungeeCord#1959]
I use [BungeeTabListPlus](https://www.spigotmc.org/threads/bungeetablistplus.10325/) on my BungeeCord server and I'm still getting this warning in console:
`[Ping Handler] -> <server name> - read timed out`
I already wrote to plugin developer and he said that it is not message from his plugin.

BungeeCord version: git:BungeeCord-Bootstrap:1.10-SNAPSHOT:0581e49:1190 
Server: Microsoft Windows Server 2008 R2

On server is running: IIS, Teamviewer, hMailServer, Filezilla, Cobian Backup, MS SQL, MySQL

BungeeCord config:

```
ip_forward: true
network_compression_threshold: 256
stats: ed4881a4-ad67-4ecf-b3ff-34a3b08e7db7
groups:
  koca2000:
  - admin
servers:
  studiodamage:
    address: localhost:25568
    restricted: false
    motd: '&9StudioDamage server(MC1.9.2)'
  hardcore:
    address: localhost:25563
    motd: '&Hardcore server(MC1.10)'
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- max_players: 20
  host: 0.0.0.0:25565
  bind_local_address: false
  ping_passthrough: true
  tab_list: GLOBAL_PING
  forced_hosts:
    hardcore.***********..cz: hardcore
    ***********.cz: studiodamage
  tab_size: 60
  force_default_server: false
  motd: '&9StudioDamage server'
  query_enabled: true
  query_port: 25565
  priorities:
  - studiodamage
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
```
