### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by agent9002** [SpigotMC/BungeeCord#2064]
**Hi there!**
I have recently been having trouble setting up my bungee, when I add more than one server to the config the whole thing breaks and I can't join the server anymore, when I remove the server from the config then the bungee server works again. If someone could help me setup the config that would be great!

Here is a list of the IP's that I need on my bungee

Bungee Server - 79.143.189.31:25933
Hub/Lobby - 79.143.189.31:25934
Prison Server - 46.4.90.149:25688
Factions Server - 149.202.83.16:41638

And here is my current config.yml

```ip_forward: false
network_compression_threshold: 256
stats: 7af52306-8999-4675-8f1c-eb14485b194d
permissions:
  default:
  - bungeecord.command.server
ip_forward: false
network_compression_threshold: 256
stats: 7af52306-8999-4675-8f1c-eb14485b194d
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: '&e&l&m--&9&8&l[&r &6&lThe ShieldMC Network &8&l]&e&l&m--&8&l[ &eRELEASED &8&l]&e&l&m-----&e&l&m ---&8&l[ &ePrison:&8&l ]&e&m----&8&l[&r &e&l Factions &8&l]&e&l&m-  &8&l[&r &e&lMore Soon &8&l] &e&l&m-                                                        '
    address: 79.143.189.31:25934
    restricted: false
timeout: 30000
listeners:
- query_port: 25934
  motd: '&1Another Bungee server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 79.143.189.31:25933
  forced_hosts:
    79.143.189.31:25934: pvp
  max_players: 600
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
```

**Comment by kamcio96** [comment]
```yml
servers:
  lobby:
    motd: '&e&l&m--&9&8&l[&r &6&lThe ShieldMC Network &8&l]&e&l&m--&8&l[ &eRELEASED &8&l]&e&l&m-----&e&l&m ---&8&l[ &ePrison:&8&l ]&e&m----&8&l[&r &e&l Factions &8&l]&e&l&m-  &8&l[&r &e&lMore Soon &8&l] &e&l&m-                                                        '
    address: 79.143.189.31:25934
    restricted: false
  prison:
    motd: '&e&l&m--&9&8&l[&r &6&lThe ShieldMC Network &8&l]&e&l&m--&8&l[ &eRELEASED &8&l]&e&l&m-----&e&l&m ---&8&l[ &ePrison:&8&l ]&e&m----&8&l[&r &e&l Factions &8&l]&e&l&m-  &8&l[&r &e&lMore Soon &8&l] &e&l&m-                                                        '
    address: 46.4.90.149:25688
    restricted: false
  factions:
    motd: '&e&l&m--&9&8&l[&r &6&lThe ShieldMC Network &8&l]&e&l&m--&8&l[ &eRELEASED &8&l]&e&l&m-----&e&l&m ---&8&l[ &ePrison:&8&l ]&e&m----&8&l[&r &e&l Factions &8&l]&e&l&m-  &8&l[&r &e&lMore Soon &8&l] &e&l&m-                                                        '
    address: 149.202.83.16:41638
    restricted: false

```
Pls use forum next time for support. Its issue tracker :wink:

https://www.spigotmc.org/forums/
