### ISSUE TITLE
"error : outdated Client" when connect to server via bungee cord

### ISSUE THREAD

**Issue by tester00131** [SpigotMC/BungeeCord#2101]
my client version is 1.7.2
my server version  is 1.7.2
I can connect direct to server (127.0.0.1:26611 or 127.0.0.1:26622) but when I try connect to bungee cord (127.0.0.1:25565 or 127.0.0.1). It always display `outdated Client` on my client and show `<-> InitialHandler has connected` on bungee command prompt below is my config.yml

```
ip_forward: false
network_compression_threshold: 256
stats: 70a0a8f6-5dbd-4c20-b578-68904e6043de
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  md_5:
  - admin
servers:
  s1:
    motd: '&1server1'
    address: 127.0.0.1:26611
    restricted: false
  s2:
    motd: '&1server2'
    address: 127.0.0.1:26622
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - s1
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 127.0.0.1:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 250
  tab_size: 60
  ping_passthrough: true
  force_default_server: true
player_limit: 250
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000

```
