### ISSUE TITLE
Bungeecord | You have no permission to execute this command! |

### ISSUE THREAD

**Issue by EmeraldSwordYT** [SpigotMC/BungeeCord#2435]
The commands:
sc (staffchat)
send (bring someone to a server)
etc etc...
I get an error like: You have no permission to execute this command!
I have OP, im bungeecord admin... and have an '*' permission.

Please help!

**Comment by Janmm14** [comment]
Please use spigotmc.org forums for help with configuration.

**Comment by HAlexTM** [comment]
Please, make sure that:
- You wrote the correct username
- The group `admin` has every permissions wrote line per line (not `*`)
```
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.send
groups:
  EmeraldSwordYT:
  - admin
```
- Close the proxy, start it again
- Close this issue
- Test if it's working, if not use `/perms` and write the output with your `config.yml` in the Spigot Forums
- Don't write config-related issues here, but just like Janmm14 said, use Spigot Forums

**Comment by ItsRyxn25** [comment]
on my bungee network how do i make myself op

**Comment by HAlex** [comment]
@ItsRyxn25 two questions for you:
Why did you use this issue to ask your question?
Why didn't you read previous comments stating that you should be using the Spigot Forums for these kinds of issues?

**Comment by ItsRyxn25** [comment]
cause i did and they didnt answer my quest

**Comment by ItsRyxn25** [comment]
thanks for replying tho

**Comment by HAlex** [comment]
@ItsRyxn25

```yaml
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.send
groups:
  YourUsername:
  - admin
```

Make sure you have something like that in your `config.yml`, replace `YourUsername` with your username.
