### ISSUE TITLE
It's not possible to empty groups and permissions

### ISSUE THREAD

**Issue by nilsbrychzy** [SpigotMC/BungeeCord#2524]
If using a plugin for permissions we don't need the configuration in `config.yml` but setting it to empty 

```
groups: 
permissions: 
```

it's resetting to

```
groups:
  md_5:
  - admin
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
```

https://github.com/SpigotMC/BungeeCord/blob/730715e68b7a6fe4b64e3b7a9b3b166d35f30abe/proxy/src/main/java/net/md_5/bungee/conf/YamlConfig.java#L85-L102

Any workaround for that or even a code fix?

Also it's not possible to remove all `forced_hosts`.
