### ISSUE TITLE
Sending to a specific server with a domain

### ISSUE THREAD

**Issue by DamonOnYT** [SpigotMC/BungeeCord#2534]
Hey, i am having a problem. i am trying to send users to my survival server when they use **ecraft-play.cf** but it is sending them to the lobby instead. just saying i use CloudFlare DNS

**BungeeCord Config**
```
forge_support: false
timeout: 30000
online_mode: true
log_commands: true
listeners:
- query_port: 25646
  motd: ''
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    ships.sknd.host: lobby
    ecraft-play.cf: survival
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25646
  max_players: 2000
  tab_size: 60
  force_default_server: false
connection_throttle: 4000
groups:
  MystingShadow:
  - admin
  jakecooper732:
  - admin
  Damon_On_Youtube:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: c288fda7-e4ca-4706-8447-0cb173d66186
permissions:
  default:
  - slashserver.Factions
  - slashserver.Skywars
  - slashserver.Bedwars
  - slashserver.Survival
  - bungeecord.server.Bedwars
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.lobby
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.lobby
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.server.Bedwars
  - slashserver.Factions
  - slashserver.Skywars
  - slashserver.Bedwars
  - slashserver.Survival
servers:
  lobby:
    motd: '&awelcome to our servers we hope you have lots of fun                                          &d1.8-1.13'
    address: 198.27.83.113:26797
    restricted: false
  Skywars:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 188.165.216.115:27496
    restricted: true
  Factions:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 145.239.130.127:25566
    restricted: false
  Bedwars:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 149.202.84.162:25594
    restricted: true
  survival:
    motd: '&cECraft MC &6- &aSurvival/n&d1.2.2-1.13'
    address: 110.20.220.7:25565
    restricted: false
player_limit: -1
```
