### ISSUE TITLE
Cannot connect to IPv6 backend servers when Bungeecord binds to IPv4 hostname/address

### ISSUE THREAD

**Issue by frebib** [SpigotMC/BungeeCord#2680]
I will provide some logs later, but there isn't much to go on. From what I can see there are no `could not connect because ..` reasons and you just get a generic netty error in the client. Also binding to a DNS hostname that is dual stack (both A and AAAA records, Bungee *only* binds to the v4 address which is unintuitive and not very helpful)

When binding Bungee to v6 (e.g. `[::]:25565`, connecting to v6 backends works fine. I'm not sure why one socket family would affect what should be unrelated sockets.

**Comment by frebib** [comment]
I just read the documentation and realised you could bind twice with two listeners, so I did that. It at least now binds to two addresses, which is correct.

The problem still remains that v4 clients cannot connect to any of the upstream servers as all of our backends are v6-only. Is there a way to make this work?

**Comment by frebib** [comment]
Example Bungeecord logs
```
09:42:56 [INFO] Listening on /<v4-address>:25501
09:42:56 [INFO] Listening on /<v4-address>:25501
09:43:07 [INFO] [/<v4-client>:49052] <-> InitialHandler has connected
09:43:08 [INFO] [ProKado] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException
09:43:08 [INFO] [ProKado] -> UpstreamBridge has disconnected
09:45:21 [INFO] [/<v4-client>:57613] <-> InitialHandler has connected
09:45:22 [INFO] [ProKado] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException
09:45:22 [INFO] [ProKado] -> UpstreamBridge has disconnected
```

Bungeecord config
```
connection_throttle_limit: 3
timeout: -1
online_mode: true
log_commands: true
network_compression_threshold: 256
listeners:
- query_port: 25577
  motd: |-
    ..
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: true
  priorities:
    ..
  bind_local_address: true
  host: '[v6-address]:25501'
  max_players: 32
  tab_size: 60
  force_default_server: false
  forced_hosts: {}
- query_port: 25577
  motd: |-
    ..
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: true
  priorities:
    ..
  bind_local_address: true
  host: <v4-address>:25501
  max_players: 32
  tab_size: 60
  force_default_server: false
  forced_hosts: {}
connection_throttle: 100
groups:
  ..
log_pings: false
ip_forward: true
prevent_proxy_connections: false
forge_support: true
inject_commands: true
disabled_commands:
- stop
- globalchat
stats: <snip>
permissions:
  ..
servers:
  survival:
    motd: 'Vanilla Survival'
    address: vanilla.minecraft.nerdhouse.io
    restricted: false
  creative:
    address: creative.minecraft.nerdhouse.io
    restricted: false
    motd: Creative Bungeecord host
player_limit: -1
```

The backends are firewalled currently so if you want to test against them let me know and we can work something out
