### ISSUE TITLE
priorities not working as described

### ISSUE THREAD

**Issue by phoenixlzx** [SpigotMC/BungeeCord#2696]
According to https://www.spigotmc.org/wiki/bungeecord-configuration-guide/

> priorities
Default: lobby
Type: List
Description: On connection of first time players, or if forcing default server, all connecting players, BungeeCord goes through this list of servers from top to bottom and tries to forward the connection to each of them. So if you would like to support multiple client versions, simply specify at least one server per version and BungeeCord will do the matching for you.

### Our setup

```
servers:
  s1132:
    motd: 'server for 1.13.2'
    address: localhost:25565
    restricted: false
  s1144:
    motd: 'server for 1.14.4'
    address: localhost:25566
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - s1132
  - s1144
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts: {}
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  proxy_protocol: false
```

### What is expected

BungeeCord sends 1.13.2 clients to s1, while sends 1.14.4 clients to s2.

### Result

I was kicked due to s1 version mismatch, while connecting with 1.14.4 client.
But if s1 is down, I can successfully connect to s2.
