### ISSUE TITLE
can't connect to bungeecord when ip_forward = true

### ISSUE THREAD

**Issue by azah** [SpigotMC/BungeeCord#2731]
In config.yml when I have `ip_forward` set to `true`, I get this error.

![image](https://user-images.githubusercontent.com/9789467/71038860-b6ebe280-211a-11ea-83c5-2fb39b4da0cb.png)

my config.yml
```
forge_support: false
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25577
  motd: '&5Portal Server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 192.168.1.22:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
connection_throttle: 4000
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: ec617ab2-0055-445a-b01a-c31aef2ecbc5
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  lobby:
    motd: 'Lobby'
    address: localhost:25565
    restricted: false
    ip_forward: true
  survival:
    motd: 'Survival'
    address: 192.168.1.24:25565
    restricted: false
    ip_forward: true
  creative:
    motd: 'Creative'
    address: 192.168.1.23:25565
    restricted: false
    ip_forward: true
player_limit: -1
```
