### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException on Linux

### ISSUE THREAD

**Issue by RimuruChan** [SpigotMC/BungeeCord#2807]
sometimes it will throw an exception called io.netty.channel.unix.Errors$NativeIoException

and i finally tested that it is because

option use-native-transport under spigot is ON.

wiki said this option is built for linux performance improvements

> Linux server performance improvements: optimized packet sending/receiving on Linux

**Comment by MrIvanPlays** [comment]
From the name of the parameter I think this disables netty, try disabling it and try connecting to your server again.

**Comment by Janmm14** [comment]
Netty cannot be disabled in spigot 1.8 or higher, since mojang adapted to netty in 1.8 (or was it 1.7 already?)

**Comment by RimuruChan** [comment]
after disable this option, it will take more time to connect other server through bungeecord
and this exception still seldom happen

**Comment by MrIvanPlays** [comment]
Weird. What build of bungeecord are you running? Can you show us your config?

**Comment by RimuruChan** [comment]
latest.

```
inject_commands: false
server_connect_timeout: 5000
remote_ping_cache: -1
custom_server_name: Inf Network
forge_support: false
always_handle_packets: false
player_limit: 300
permissions:
  default:
  - NoPerm
timeout: 30000
log_commands: true
network_compression_threshold: 256
online_mode: false
servers:
  login:
    motd: Login
    address: 127.0.0.1:20000
    restricted: false
  lobby#1:
    motd: Lobby#1
    address: 127.0.0.1:20011
    restricted: false
  lobby#2:
    motd: Lobby#2
    address: 127.0.0.1:20012
    restricted: false
  lobby#3:
    motd: Lobby#3
    address: 127.0.0.1:20013
    restricted: false
  lobby#4:
    motd: Lobby#4
    address: 127.0.0.1:20014
    restricted: false
  lobby#5:
    motd: Lobby#5
    address: 127.0.0.1:20015
    restricted: false
  arcadeLobby#1:
    motd: ArcadeLobby
    address: 127.0.0.1:20021
    restricted: false
  ptllobby#1:
    motd: PtlLobby
    address: 127.0.0.1:20031
    restricted: false
  bedwars:
    motd: Bedwars
    address: 127.0.0.1:20050
    restricted: false
  build:
    motd: Build
    address: 127.0.0.1:19999
    restricted: true
  bridge:
    motd: Bridge
    address: 127.0.0.1:20063
    restricted: false
  pvp2:
    motd: Pvp
    address: 127.0.0.1:20060
    restricted: false
  rushbed:
    motd: RushBed
    address: 127.0.0.1:20062
    restricted: false
  thepit:
    motd: Thepit
    address: 127.0.0.1:20091
    restricted: false
  skywars:
    motd: skywars
    address: 127.0.0.1:20092
    restricted: false
  bedwars#1:
    motd: Bedwars#1
    address: 127.0.0.1:20064
    restricted: false
  bedwars#2:
    motd: Bedwars#2
    address: 127.0.0.1:20065
    restricted: false
  bedwars#3:
    motd: Bedwars#3
    address: 127.0.0.1:20066
    restricted: false
  bedwars#4:
    motd: Bedwars#4
    address: 127.0.0.1:20067
    restricted: false
  bedwars#5:
    motd: Bedwars#5
    address: 127.0.0.1:20068
    restricted: false
  bedwars#6:
    motd: Bedwars#6
    address: 127.0.0.1:20069
    restricted: false
  bedwars#7:
    motd: Bedwars#7
    address: 127.0.0.1:20070
    restricted: false
  bedwars#8:
    motd: Bedwars#8
    address: 127.0.0.1:20071
    restricted: false
  bedwars#9:
    motd: Bedwars#9
    address: 127.0.0.1:20072
    restricted: false
  bedwars#10:
    motd: Bedwars#10
    address: 127.0.0.1:20073
    restricted: false
  bedwars#11:
    motd: Bedwars#11
    address: 127.0.0.1:20074
    restricted: false
  bedwars#12:
    motd: Bedwars#12
    address: 127.0.0.1:20075
    restricted: false
  bedwars#13:
    motd: Bedwars#13
    address: 127.0.0.1:20076
    restricted: false
  bedwars#14:
    motd: Bedwars#14
    address: 127.0.0.1:20077
    restricted: false
  bedwars#15:
    motd: Bedwars#15
    address: 127.0.0.1:20078
    restricted: false
  bedwars#16:
    motd: Bedwars#16
    address: 127.0.0.1:20079
    restricted: false
  rpg:
    motd: Rpg
    address: 127.0.0.1:20042
    restricted: false
  rpg#2:
    motd: rpg#2
    address: 127.0.0.1:20043
    restricted: false
  skyblock:
    motd: Skyblock
    address: 127.0.0.1:20045
    restricted: false
  ihb:
    motd: IHB
    address: 127.0.0.1:20040
    restricted: false
  survival:
    motd: Survival
    address: 127.0.0.1:20041
    restricted: false
  tianjie:
    motd: Tianjie
    address: 127.0.0.1:20044
    restricted: false
  murder:
    motd: Murder
    address: 127.0.0.1:20061
    restricted: false
  zombie#1:
    motd: Zombie#1
    address: 127.0.0.1:20093
    restricted: false
  zombie#2:
    motd: Zombie#2
    address: 127.0.0.1:20094
    restricted: false
  zombie#3:
    motd: Zombie#3
    address: 127.0.0.1:20095
    restricted: false
listeners:
- query_port: 25565
  motd: Inf Network BungeeCord
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts: {}
  ping_passthrough: false
  priorities:
  - login
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 2020
  tab_size: 80
  force_default_server: true
ip_forward: true
remote_ping_timeout: 5000
prevent_proxy_connections: false
disabled_commands:
- perms
connection_throttle: 4000
stats: 9482004b-558c-42a2-8c35-60a45429fb3c
connection_throttle_limit: 3
groups: {}
log_pings: true

```
