### ISSUE TITLE
Forced Hosts

### ISSUE THREAD

**Issue by eddster2309** [SpigotMC/BungeeCord#2809]
Hi i am trying to setup forced host and its not working.

I have tryed doing things suggested in this: [https://github.com/SpigotMC/BungeeCord/issues/1532](https://github.com/SpigotMC/BungeeCord/issues/1532)

My DNS setup is as followed:

So i don't have a static ip. So i use No-IP to update these hostnames:

- eddsterhunger.ddns.net
- eddsterpvp.ddns.net
- eddstersurvive.ddns.net
- eddsteruhc.ddns.net

I then have CNAME records for my own domain: eddster.info. The Setup is as followed:

- hunger.eddster.info is eddsterhunger.ddns.net 
- pvp.eddster.info is eddsterpvp.ddns.net
- survival.eddster.info is eddstersurvive.ddns.net
- creative.eddster.info is eddsteruhc.ddns.net

Also i have a dynamic dns going directly through Google Domains to minecraft.eddster,info which i would like to take the player to the server they were last on.

My Bungee Config is as followed:

```
listeners:
- query_port: 25565
  motd: '&1Eddsters Network'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    eddstersurvive.ddns.net: Survival
    eddsterpvp.ddns.net: KitPVP
    eddsterhunger.ddns.net: HungerGames
    eddsteruhc.ddns.net: Creative
  ping_passthrough: false
  priorities:
  - HungerGames
  - Survival
  - KitPVP
  - Creative
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: 249822d6-e325-4c82-aff9-6cc5cf378375
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  HungerGames:
    motd: '&1Eddsters Server'
    address: localhost:25571
    restricted: false
  Survival:
    motd: '&1Eddsters Server'
    address: localhost:25572
    restricted: false
  Creative:
    motd: '&1Eddsters Server'
    address: localhost:25573
    restricted: false
  KitPVP:
    motd: '&1Eddsters Server'
    address: localhost:25574
    restricted: false
```

My issue is as followed:

Currently my all my addresses go to Hunger Games,

Thanks in advanced
