### ISSUE TITLE
[Suggestion] A global plugins folder or a config to append plugins & config folders to specified servers

### ISSUE THREAD

**Issue by Jadiction** [SpigotMC/BungeeCord#2964]
Not sure if this is possible, or if there's something that already serves this purpose, but I would be very interested in a way to "globalize" certain plugins for some of my worlds. For example, if I use Vault for every plugin, I could drop the vault jar and the vault config folder in a "GLOBAL_PLUGINS" folder, and all worlds would load it. 

An even better method would be a config that links certain folders to append to servers. For example:
Let's say `world1` and `world2` have Vault and Factions. With this suggested config, you could globalize the .jars (so when you update, you only have to update one folder & jar) and perhaps even use the same plugin configuration so you don't have to modify each one.

Perhaps something like this:
```
global_plugins:
  vault:
    servers:
    - 'world1'
    - 'world2'
    config: true
  factions:
    servers:
    - 'world1'
    - 'world2'
    config: false
#since config is false, it will load the config folder in the specified world's plugin directory, but load the global .jar in the "global_plugins" directory.
```
To know which .jar and folder to use for appending, you may have to regex the name and search or have user specify the folder & .jar names in the config.
