### ISSUE TITLE
Admin cannot execute admin's commands

### ISSUE THREAD

**Issue by AlonsoGMR** [SpigotMC/BungeeCord#2988]
I set in my config.yml file of the bungee that im admin and set permissions for  admin:
```
`permissions:
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  groups:
  MyUsername:
  - admin`

```

but I can't use bungee commands
