### ISSUE TITLE
[Severe] Console error

### ISSUE THREAD

**Issue by ISlipperyCedder** [SpigotMC/BungeeCord#2997]
I keep getting this error how do I fix it. My bungee server is on 1.16.4 whilst the hub is on 1.12.2

16:04:46 [SEVERE] Exception in thread "main" 

16:04:46 [SEVERE] java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.Collection

16:04:46 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:234)

16:04:46 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:85)

16:04:46 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)

16:04:46 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)

16:04:46 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Here is my configuration file:
https://pastebin.com/kki2FkvR

**Comment by Janmm14** [comment]
Configuration error. You have an invalid, incomplete, partly outdated config.

Usually configuration problems are not meant for this issue tracker, but for the spigotmc.org forums.

You can find the current default config here: https://www.spigotmc.org/wiki/bungeecord-configuration-guide/

I edited your config:
```yaml
groups:
  ISlipperyCedder:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: -1
stats: bdd33aff-949a-479a-83e3-63a4bb26797f
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.send
  - bungeecord.*
  - bungeecord.command.*
  - bungeecord.command.find
  - bungeecord.command.list
  - bungeecord.command.reload
  - bungeecord.command.ip

listeners:
- motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
  proxy_protocol: false
timeout: 30000
connection_throttle: 4000
servers:
  hub:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 178.33.194.176:2175
    restricted: false
  survival:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 178.33.194.176:2173
    restricted: false
  fallback:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 178.33.194.176:2174
    restricted: false
  skywars:
    motd: '&1SkyWars 1.12.2'
    address: 178.33.194.176:2179
    restricted: false
  tntrun:
    motd: '&1TnTRun 1.12.2'
    address: 178.33.194.176:2186
    restricted: false
  buildbattle:
    motd: '&1BuildBattle 1.12.2'
    address: 178.33.194.176:2200
    restricted: false
  factions:
    motd: '&1Factions 1.12.2'
    address: 178.33.194.176:2202
    restricted: false
  kitpvp:
    motd: '&1KitPVP 1.12.2'
    address: 178.33.194.176:2204
    restricted: false
  skyblock:
    motd: '&1SkyBlock 1.12.2'
    address: 178.33.194.176:2206
    restricted: false
  prison:
    motd: '&1Prison 1.12.2'
    address: 178.33.194.176:2208
    restricted: false
  creative:
    motd: '&1Creative 1.12.2'
    address: 178.33.194.176:2210
    restricted: false
ip_forward: false
online_mode: true
```
