### ISSUE TITLE
Ping is 0

### ISSUE THREAD

**Issue by DeathMario** [SpigotMC/BungeeCord#3175]
When i do /ping on a server that is on the same machine as the bungeecord proxy, it shows the real ping...

But when the server is not on the same machine shows ping as 0.

This is my config:

```
disabled_commands:
- disabledcommandhere
servers:
  hcf:
    address: 172.18.0.1:4001
    motd: '&aYay, hcf!'
    restricted: false
  hub:
    address: 129.151.112.242:4000
    default: true
    motd: '&1Just another BungeeCord - Forced Host'
    restricted: false
  kitmap:
    address: 172.18.0.1:25567
    motd: '&1Kitmap xd'
    restricted: false
  practice:
    address: other.domain:10140
    motd: '&lKitmap xd'
    restricted: false
  test:
    address: 172.x.x.x:5004
    motd: Aja, test
    restricted: false
```
