### ISSUE TITLE
Kicked whilst connecting to Hub: Failed to verify username!

### ISSUE THREAD

**Issue by ghost** [SpigotMC/BungeeCord#394]
Hi there.
I'm quite new to BungeeCord and I've been trying to set up a server.

I'm using [build 461](http://ci.md-5.net/job/BungeeCord/461/). I'm sure I have everything set up right but when I connect to the server it says "Kicked whilst connecting to Hub: Failed to verify username!". **I definitely have a premium account.**

As I said, I am quite new to BungeeCord but I am also a programmer so I decided to look at what was happening in my server.properties. Online mode, I know, has to be set to false for all the servers you want to use Bungee on. It had suddenly set itself to true. I set it to false and ran the server.

The same kick happened. I stopped Bungee, my Hub server and my HG server and looked at the server.properties. It had set online mode back to true!

Could someone please tell me what's happening? My config.yml and server.properties are below.

Many thanks.

config.yml:

``` YAML
tab_list: GLOBAL_PING
groups:
  pbpaperclips:
  - admin
player_limit: -1
stats: 71c01344-ae98-4826-af0f-79b41ae86514
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- fallback_server: Hub
  max_players: 1000000
  host: localhost:25565
  tab_size: 60
  force_default_server: false
  texture_size: 16
  motd: "&l&4&k!&r&l&4Bungeeeee!&k!"
  default_server: Hub
  forced_hosts:
    pvp.md-5.net: pvp
timeout: 30000
servers:
  Hub:
    address: localhost:25566
    restricted: false
 HG:
    address: localhost:25567
    restricted: false
online_mode: true
```

server.properties:

``` YAML
#Minecraft server properties
#Mon May 27 09:26:48 BST 2013
generator-settings=
allow-nether=true
level-name=world
enable-query=false
allow-flight=false
server-port=25566
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
hardcore=false
snooper-enabled=true
texture-pack=
online-mode=true (Usually set to false but changes itself...)
pvp=false
difficulty=1
gamemode=0
max-players=1000000
spawn-monsters=false
generate-structures=true
view-distance=10
spawn-protection=16
motd=Don't look at meh... Ah am teh hub...
```
