### ISSUE TITLE
Command aliases [enhancement]

### ISSUE THREAD

**Issue by Moehritz** [SpigotMC/BungeeCord#662]
Add configurable command aliases, eg /hub -> /server hub

config.yml:

``` yaml
aliases:
- name: hub
  toExecute: server hub
- name: pvp
  toExecute: server pvp
```
